- name: Create network config
  copy:
    content: "{{ dns['network_config'] }}"
    dest: /root/network.sh
    mode: +x
  register: network_config

- name: Apply network config
  shell: bash /root/network.sh
  when: network_config.changed

- name: Set hosts file
  copy:
    content: |
      127.0.0.1	localhost
      ::1     localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
    dest: /etc/hosts

- name: Check hostname
  shell: hostname
  register: node_hostname
  changed_when: False

- name: Set persistent hostname
  shell: hostnamectl set-hostname "{{ inventory_hostname }}"
  when: node_hostname.stdout != inventory_hostname
