# config.yml

development: true
ssh-key: /home/nate/ssh-key

dns:
    rname: info.delivr.dev
    nameservers:
        - ns1.delivr.dev
        - ns2.delivr.dev

email:
    username: noreply@delivr.dev
    password: fake
    server: fake

proxy:
    server4: 192.0.2.100
    server6: 2001:db8::100
