- name: Copy BIRD2 config
  template:
    src: bird.j2
    dest: /etc/bird/bird.conf
  vars:
    asn: 34553
    selected_ipv4_prefix: "{{ dns['prefix4'] }}"
    selected_ipv6_prefix: "{{ dns['prefix6'] }}"
    collector_ip: "{{ collector['host'] }}"
  register: bird_config

- name: Apply BIRD config
  shell: birdc config
  when: bird_config.changed
