- name: Install
  hosts: cache
  tasks:
    - include_vars: vars.yml

    - name: Add debian sid repo
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - deb http://deb.debian.org/debian/ sid main
        - deb [trusted=yes] https://apt.fury.io/caddy/ /

    - name: Set default release
      copy:
        content: APT::Default-Release "stable";
        dest: /etc/apt/apt.conf.d/default-release

    - name: Install varnish, ufw
      apt:
        update_cache: yes
        pkg:
          - varnish
          - ufw

#    TODO: ufw config

    - name: Install BIRD2 from sid
      apt:
        name: bird2
        default_release: sid

    - name: Copy BIRD2 config
      template:
        src: bird.j2
        dest: /etc/bird/bird.conf
      vars:
        asn: 34553
        ipv4_prefix: "{{ cache_ipv4_prefix }}"
        ipv6_prefix: "{{ cache_ipv6_prefix }}"
      register: bird_config

    - name: Apply BIRD config
      shell: birdc config
      when: bird_config.changed

    - name: Create network config
      copy:
        content: "{{ cache_config }}"
        dest: /root/network.sh
        mode: +x
      register: network_config

    - name: Apply network config
      shell: /root/network.sh
      when: network_config.changed

    - name: Copy varnish service
      template:
        src: varnish.service.j2
        dest: /lib/systemd/system/varnish.service
      register: varnish_config

    - name: Restart varnishd
      systemd:
        daemon_reload: yes
        name: varnish
        state: restarted
      when: varnish_config.changed

# TODO: Add varnish config
