name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Build frontend

      - name: Build frontend and docs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cd frontend/ ; yarn install ; yarn build
      - run: cd docs/ ; yarn install ; yarn build

      # Copy to server

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/home/nate/delivr/"

#      # Restart backend processes
#
#      - name: Restart orchestrator process
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: sudo systemctl restart delivr-orchestrator
#
#      - name: Restart API process
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: sudo systemctl restart delivr-api
